---

version: '3'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=123
      - TZ=Europe/London
    volumes:
      - ../tests/docker_configs/sonarr/config.yml:/config/config.yml:rw
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=123
      - TZ=Europe/London
    volumes:
      - ../tests/docker_configs/radarr/config.yml:/config/config.yml:rw
    ports:
      - 7878:7878
    restart: unless-stopped
