---

version: '3'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=Europe/London
    volumes:
      - ./tests/docker_configs/sonarr/config.xml:/config/config.xml:rw
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=Europe/London
    volumes:
      - ./tests/docker_configs/radarr/config.xml:/config/config.xml:rw
    ports:
      - 7878:7878
    restart: unless-stopped
