name: Test

on:
  workflow_dispatch:

jobs:
  code-quality:

    name: 📊 Check code quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run containers
        run: docker-compose -f .ci/docker-compose.yml up -d
      - name: Sleep for 1 min
        run: sleep 60s
        shell: bash
      - name: Add hosts
        run: |
          sudo echo "127.0.0.1 sonarr readarr radarr lidarr prowlarr deluge jackett" | sudo tee -a /etc/hosts
      - name: check ports
        run: docker ps
      - name: curl
        run: curl http://radarr:7878
      - name: check api key
        run: docker compose exec -T radarr ls -l 
      - name: check local config
        run: cat tests/docker_configs/radarr/config.xml
      - name: Inspect container
        run: docker inspect radarr
      - name: 🧪 Check tests are passing
        run: |
          pip install poetry nox
          nox -s test


